# Implementing numpuy concepts

# Import library

In [103]:
import numpy as np

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
np.array([4,2,3,2,3])

array([4, 2, 3, 2, 3])

In [4]:
x=np.array([4,2,3,2,3])

In [5]:
x

array([4, 2, 3, 2, 3])

In [6]:
print(x)

[4 2 3 2 3]


In [7]:
x.mean()

2.8

In [8]:
x.sum()

14

In [9]:
sum(x)

14

In [10]:
x.min()

2

In [11]:
x.max()

4

In [12]:
x=x.reshape(-1,1)

In [13]:
x.ndim

2

In [14]:
x

array([[4],
       [2],
       [3],
       [2],
       [3]])

In [15]:
list1=[2,3,23,24,3]
list2=[2,3,2,3,4]
y=np.array([list1,list2])

In [16]:
print(y)

[[ 2  3 23 24  3]
 [ 2  3  2  3  4]]


In [17]:
list1=[2,3,23,24,3]
list2=[2,3,2,3,4]
w=np.concatenate([list1,list2])

In [18]:
print(w)

[ 2  3 23 24  3  2  3  2  3  4]


In [19]:
q=np.array([list1+list2])

In [20]:
print(q)

[[ 2  3 23 24  3  2  3  2  3  4]]


In [21]:
y[1:0]

array([], shape=(0, 5), dtype=int32)

In [22]:
np.isin(w,24)

array([False, False, False,  True, False, False, False, False, False,
       False])

In [23]:
np.where(w==24)

(array([3], dtype=int64),)

In [26]:
p=np.linspace(10,100,10,dtype=int)

In [29]:
p

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [30]:
x.shape

(5, 1)

In [33]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [51]:
k=np.ones(90,dtype=int)

In [52]:
k

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [53]:
k.ndim

1

In [54]:
k.shape

(90,)

In [55]:
l=np.where(k==2)

In [56]:
l

(array([], dtype=int64),)

In [57]:
print(l)

(array([], dtype=int64),)


In [59]:
k.reshape(-1,1)

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [60]:
k.reshape(1,-1)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1]])

In [91]:
n=0
for i in range(0,20):
    i=i+n
    print(n)

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0


In [81]:
n

()

In [92]:
p=np.arange(20,1,-1)

In [97]:
p

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2])

In [75]:
np.arange(1,20,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [98]:
np.unique(k)

array([1])

In [99]:
np.unique(p)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20])

In [100]:
p.sort()

In [102]:
p

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20])